set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
# set -ga terminal-overrides ",screen-256color*:Tc"
# set-option -g default-terminal "screen-256color"
set-option -g default-shell /usr/bin/fish

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

# POPUP WINDOWS
# These two shortcuts provide popup windows in tmux. The lowercase version
# makes a popup that named uniquely to the working directory. This is great
# for making a popup window in a coding project.
#
# The uppercase version makes a "global" popup window. Great for persisting
# things globally for a long period of time.
bind g run-shell '\
    POPUP_NAME="popup-$(basename "#{pane_current_path}" | tr -cd "a-zA-Z0-9-")"; \
    if [ "#{session_name}" = "$POPUP_NAME" ]; then \
        tmux detach-client; \
    else \
        tmux display-popup -d "#{pane_current_path}" -xC -yC -w 80% -h 75% -E "tmux attach-session -t $POPUP_NAME || tmux new-session -s $POPUP_NAME"; \
    fi \
'

bind G run-shell '\
    POPUP_NAME="popup-global"; \
    if [ "#{session_name}" = "$POPUP_NAME" ]; then \
        tmux detach-client; \
    else \
        tmux display-popup -xC -yC -w 80% -h 75% -E "tmux attach-session -t $POPUP_NAME || tmux new-session -s $POPUP_NAME"; \
    fi \
'

# set -g status-position top
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -r m resize-pane -Z

set -g mouse on

set-option -g status-interval 1
# set-window-option -g mode-keys vi
#
# bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
# bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

set -s set-clipboard on

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "tmux-plugins/tmux-resurrect"
# set -g @plugin "tmux-plugins/tmux-yank"
# set -g @plugin 'tmux-plugins/tmux-continuum'

# resurrect
set -g @resurrect-strategy-nvim 'session'

# set -g status-bg '#08273A'
# set -g status-fg '#fafafa'
# set -g status-style 'bg=#333333 fg=#5eacd3'
set -g status-style 'bg=#282C3D fg=#84ABF4'
# set -s set-clipboard external

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
